### ISSUE TITLE
dotnet 2.0.0 not supported

### ISSUE THREAD

**Issue by chrishaly** [aspnet/Blazor-Hackathon#5]
dotnet 2.0.0 was installed but when run error occurred. 

> dotnet blazor serve
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0-preview3-25512-01' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.0-preview3-25512-01'.

**Comment by natemcmaster** [comment]
Closing. This isn't a supported project. It was just an experience for a summer hackathon.

https://github.com/aspnet/Blazor-Hackathon#why-isnt-there-an-issue-tracker-how-do-i-file-issues
